### ISSUE TITLE
undefined method `default_assignee' for nil:NilClass

### ISSUE THREAD

**Issue by massdest** [giddie/redmine_default_assign#34]
Hello, everything works fine, except url like this: 

https://fakedomain.com/issues/new?issue[project_id]=34 - return 500 error

```
Started GET "/issues/new?issue[project_id]=34" for 46.148.111.199 at 2016-05-26 11:30:52 +0300
Processing by IssuesController#new as HTML
  Parameters: {"issue"=>{"project_id"=>"34"}}
  Current user: admin (id=8)
  Rendered issues/_form.html.erb (4.1ms)
  Rendered issues/new.html.erb within layouts/base (4.9ms)
Completed 500 Internal Server Error in 44ms (ActiveRecord: 8.4ms)

ActionView::Template::Error (undefined method `default_assignee' for nil:NilClass):
    1: <%= labelled_fields_for :issue, @issue do |f| %>
    2: <%= call_hook(:view_issues_form_details_top, { :issue => @issue, :form => f }) %>
    3: <%= hidden_field_tag 'form_update_triggered_by', '' %>
    4: 
    5: <% if @issue.safe_attribute? 'is_private' %>
  plugins/redmine_default_assign/lib/default_assign/hooks/default_assign_issues_hooks.rb:12:in `view_issues_form_details_top'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/_form.html.erb:2:in `block in _app_views_issues__form_html_erb__1500603365173931466_105902640'
  app/helpers/application_helper.rb:1037:in `labelled_fields_for'
  app/views/issues/_form.html.erb:1:in `_app_views_issues__form_html_erb__1500603365173931466_105902640'
  app/views/issues/new.html.erb:11:in `block in _app_views_issues_new_html_erb___775629794838714344_106715020'
  app/helpers/application_helper.rb:1030:in `labelled_form_for'
  app/views/issues/new.html.erb:5:in `_app_views_issues_new_html_erb___775629794838714344_106715020'
  app/controllers/issues_controller.rb:130:in `block (2 levels) in new'
  app/controllers/issues_controller.rb:129:in `new'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Those urls from gnatt plugin - https://www.easyredmine.com/redmine-gantt-plugin

Redmine version: 3.2.1.stable.15287
Plugin version from git: 
```
commit 0db52268bee67e10ad00a5a30b9b865293516ab7
Author: Paul Gideon Dann <pdgiddie@gmail.com>
Date:   Thu May 19 15:06:10 2016 +0100

    Fix dodgy indentation
```

**Comment by giddie** [comment]
Can you try it now?

**Comment by massdest** [comment]
Seems to work, thank you.
